import {
  CATALOG_GENERATE_OBJECT_IDS,
  promoteCatalogFurnitureToGenerate,
} from "../assets/catalog-generate.js";
import type { SceneObject, SceneSpec, WorldSnapshot } from "../schema/index.js";
import { instantiateSceneSpecScaffolds } from "../spatial/instantiate-scene-spec.js";
import type { UePublishAsset } from "./ue-world-runtime-client.js";

/**
 * zh: 门/桌/杯的 I23D 网格。标签与吧台相同，永不声称世界模型。
 * en: I23D meshes for door/table/cup. Same label as the bar; never a world-model claim.
 */
export const CATALOG_FURNITURE_SOURCE_LABEL = "http-native-mesh";

export type CatalogFurnitureMesh = {
  objectId: string;
  bytes: Uint8Array;
};

export type CatalogFurnitureStaged = {
  objectId: string;
  hash: string;
  posixPath: string;
};

export type CatalogFurniturePublish = {
  objects: SceneObject[];
  assets: UePublishAsset[];
};

/**
 * zh: 从已提交物件 + 生成字节组发布条目。缺件则 undefined。
 * en: Build publish entries from committed objects plus generated bytes. Undefined when none match.
 */
export function buildCatalogFurniturePublish(
  objects: SceneObject[],
  meshes: CatalogFurnitureMesh[],
): CatalogFurniturePublish | undefined {
  const byId = new Map(meshes.map((mesh) => [mesh.objectId, mesh]));
  const selected = objects.filter((object) => byId.has(object.sceneObjectId));
  if (selected.length === 0) {
    return undefined;
  }
  return {
    objects: selected,
    assets: selected.map((object) => {
      const mesh = byId.get(object.sceneObjectId);
      if (mesh === undefined) {
        throw new Error(`missing furniture mesh ${object.sceneObjectId}`);
      }
      return {
        bytes: mesh.bytes,
        originalFilename: `${object.sceneObjectId}.glb`,
        objectId: object.sceneObjectId,
        bakedWorldSpace: false,
        sourceLabel: CATALOG_FURNITURE_SOURCE_LABEL,
        claimsWorldModelGeneration: false,
      };
    }),
  };
}

/**
 * zh: 把门/桌/杯的包内哈希写回快照，并把 SceneSpec 路由升成 generate。不是世界模型。
 * en: Write door/table/cup pack hashes into the snapshot and promote SceneSpec routes. Not world-model.
 */
export function applyGeneratedFurniture(
  snapshot: WorldSnapshot,
  spec: SceneSpec,
  staged: CatalogFurnitureStaged[],
): { snapshot: WorldSnapshot; spec: SceneSpec } {
  const promoted = promoteCatalogFurnitureToGenerate(spec);
  const extras = instantiateSceneSpecScaffolds(promoted, snapshot.objects);
  const merged = [...snapshot.objects, ...extras];
  const byId = new Map(staged.map((row) => [row.objectId, row]));
  const objects = merged.map((object) => {
    const row = byId.get(object.sceneObjectId);
    if (row === undefined) {
      return object;
    }
    return {
      ...object,
      assetRefs: [
        row.posixPath,
        ...object.assetRefs.filter((ref) => !/\.glb$|\.gltf$/i.test(ref)),
      ],
      materialRefs: object.materialRefs.filter(
        (ref) => !/^mat-(oak|ceramic)-/.test(ref),
      ),
    };
  });
  const addedIds = extras
    .map((object) => object.sceneObjectId)
    .filter((id) => byId.has(id));
  const regions = snapshot.regions.map((region) => {
    if (region.kind !== "interior" || addedIds.length === 0) {
      return region;
    }
    const objectRefs = [...region.objectRefs];
    for (const id of addedIds) {
      if (!objectRefs.includes(id)) {
        objectRefs.push(id);
      }
    }
    return { ...region, objectRefs };
  });
  return {
    spec: promoted,
    snapshot: {
      ...snapshot,
      objects,
      regions,
      sceneSpec: promoted,
      assetManifest: mergeManifest(
        snapshot.assetManifest,
        staged.map((row) => ({ posixPath: row.posixPath, hash: row.hash })),
      ),
    },
  };
}

export function catalogFurnitureIds(): readonly string[] {
  return CATALOG_GENERATE_OBJECT_IDS;
}

function mergeManifest(
  current: WorldSnapshot["assetManifest"],
  extra: WorldSnapshot["assetManifest"],
): WorldSnapshot["assetManifest"] {
  const byPath = new Map<string, { posixPath: string; hash: string }>();
  for (const entry of current) {
    byPath.set(entry.posixPath, entry);
  }
  for (const entry of extra) {
    byPath.set(entry.posixPath, entry);
  }
  return [...byPath.values()];
}
