/**
 * zh: schema 模块公开出口。无 fs、无网络。
 * en: Public schema exports. No fs, no network.
 */
export { EdgeType } from "./edge-types.js";
export { NodeType } from "./node-types.js";
export {
  assetSidecarSchema,
  edgeRecordSchema,
  graphFileSchema,
  nodeRecordSchema,
  sessionFileSchema,
  type AssetNode,
  type AssetSidecar,
  type ClaimNode,
  type EdgeRecord,
  type EntityNode,
  type EventNode,
  type GraphFile,
  type NodeRecord,
  type ObjectNode,
  type PlaceNode,
  type SessionFile,
  type WorldNode,
} from "./graph-file.js";
export { chronicleEventSchema, type ChronicleEvent } from "./chronicle.js";
export {
  TOOL_NAMES,
  toolInputSchema,
  toolResultSchema,
  type AttachInput,
  type ExportInput,
  type GoInput,
  type LookInput,
  type RememberInput,
  type RelateInput,
  type SayInput,
  type SpawnInput,
  type ToolName,
  type ToolResult,
} from "./tool-io.js";
export {
  aabbSchema,
  assetPlanItemSchema,
  assetPlanSchema,
  assetPlanStatusSchema,
  calibrationPlanSchema,
  candidateRevisionSchema,
  commandResultSchema,
  commitRecordSchema,
  coordinateFrameSchema,
  exportManifestSchema,
  FACTORY_MANIFEST_ASSET_EXT,
  factoryManifestItemSchema,
  factoryManifestSchema,
  factoryValidationSchema,
  generationPlanSchema,
  GLOBAL_DOCUMENT_IDS,
  globalProfileSchema,
  headFileSchema,
  intentKindSchema,
  jobRecordSchema,
  observationBundleSchema,
  playerStateSchema,
  providerCapabilitiesSchema,
  referenceBundleSchema,
  regionRevisionSchema,
  ruleDocumentSchema,
  runtimeSnapshotSchema,
  SCENE_SPEC_ASSET_EXT,
  sceneObjectSchema,
  sceneSpecObjectSchema,
  sceneSpecRefSchema,
  sceneSpecRegionSchema,
  sceneSpecRouteSchema,
  sceneSpecSchema,
  sceneSpecSourceSchema,
  sessionRegistrySchema,
  solarWmExperimentSchema,
  transformSchema,
  validationReportSchema,
  vec3Schema,
  visualAcceptanceSchema,
  WORLD_DOCUMENT_IDS,
  worldCommandSchema,
  worldEventSchema,
  worldRulesSchema,
  worldSessionRecordSchema,
  worldSnapshotSchema,
  type Aabb,
  type AssetPlan,
  type AssetPlanItem,
  type AssetPlanStatus,
  type CalibrationPlan,
  type CandidateRevision,
  type CheckResult,
  type CommandMode,
  type CommandOrigin,
  type CommandResult,
  type CommitRecord,
  type CoordinateFrame,
  type ExportManifest,
  type FactoryManifest,
  type FactoryManifestItem,
  type FactoryValidation,
  type FreezeState,
  type GenerationPlan,
  type GlobalProfile,
  type HeadFile,
  type IntentKind,
  type JobKind,
  type JobPurpose,
  type JobRecord,
  type JobStatus,
  type Mobility,
  type ObservationBundle,
  type PlayerState,
  type ProviderCapabilities,
  type QualityGrade,
  type ReferenceBundle,
  type RegionRevision,
  type RuleDocument,
  type RuleScope,
  type RunState,
  type RuntimeSnapshot,
  type ScaleStatus,
  type SceneObject,
  type SceneSpec,
  type SceneSpecObject,
  type SceneSpecRef,
  type SceneSpecRegion,
  type SceneSpecRoute,
  type SceneSpecSource,
  type SessionLifecycle,
  type SessionRegistry,
  type SolarWmExperiment,
  type Transform,
  type ValidationCheck,
  type ValidationReport,
  type Vec3,
  type VisualAcceptance,
  type WorldCommand,
  type WorldEvent,
  type WorldRuleClause,
  type WorldRules,
  type WorldSessionRecord,
  type WorldSnapshot,
} from "./v1/index.js";
export {
  renderClipSchema,
  renderResultSchema,
  renderStillSchema,
  renderViewSchema,
  type RenderClip,
  type RenderResult,
  type RenderStill,
  type RenderView,
} from "./render.js";
